# Generated by Django 6.0.6 on 2026-06-10 00:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaregiverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.CharField(choices=[('beginner', '1年以下'), ('junior', '1-3年'), ('senior', '3-5年'), ('expert', '5年以上')], default='beginner', max_length=20)),
                ('service_types', models.JSONField(default=list, help_text='可提供服务：遛狗、陪玩、拍照、喂药等')),
                ('pet_types', models.JSONField(default=list, help_text='可照顾宠物类型：狗、猫、兔子等')),
                ('video_url', models.URLField(blank=True, help_text='宠物相处视频')),
                ('daily_capacity', models.IntegerField(default=2, help_text='每日可照顾宠物数量')),
                ('price_per_day', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('rating', models.FloatField(default=0.0, help_text='平均评分')),
                ('review_count', models.IntegerField(default=0, help_text='评价数量')),
                ('completed_orders', models.IntegerField(default=0, help_text='完成订单数')),
                ('is_verified', models.BooleanField(default=False, help_text='是否实名认证')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FosterRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='详细需求说明')),
                ('services', models.JSONField(default=list, help_text='期望服务：遛狗、陪玩、拍照、喂药等')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('district', models.CharField(help_text='所在片区', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(default=39.9042)),
                ('longitude', models.FloatField(default=116.4074)),
                ('budget', models.DecimalField(decimal_places=2, help_text='预算（元/天）', max_digits=10)),
                ('status', models.CharField(choices=[('open', '寻找代养中'), ('matched', '已匹配代养人'), ('confirmed', '已确认订单'), ('completed', '已完成'), ('cancelled', '已取消')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('matched_caregiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matched_requests', to='api.caregiverprofile')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foster_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', '待确认'), ('active', '进行中'), ('completed', '已完成'), ('cancelled', '已取消'), ('disputed', '有争议')], default='pending', max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('owner_reviewed', models.BooleanField(default=False)),
                ('caregiver_reviewed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_caregiver', to=settings.AUTH_USER_MODEL)),
                ('foster_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='api.fosterrequest')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_owner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('pet_type', models.CharField(choices=[('dog', '狗'), ('cat', '猫'), ('rabbit', '兔子'), ('bird', '鸟'), ('other', '其他')], max_length=20)),
                ('breed', models.CharField(help_text='品种', max_length=100)),
                ('age', models.FloatField(help_text='年龄（岁）')),
                ('gender', models.CharField(choices=[('male', '公'), ('female', '母'), ('unknown', '未知')], max_length=10)),
                ('weight', models.FloatField(blank=True, help_text='体重（kg）', null=True)),
                ('personality', models.TextField(help_text='性格特点，如：温顺、活泼、胆小等')),
                ('diet_restrictions', models.TextField(blank=True, help_text='饮食禁忌')),
                ('health_notes', models.TextField(blank=True, help_text='健康状况说明')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='pets/')),
                ('is_vaccinated', models.BooleanField(default=False, help_text='是否已接种疫苗')),
                ('is_neutered', models.BooleanField(default=False, help_text='是否已绝育')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='fosterrequest',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foster_requests', to='api.pet'),
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '主人评价'), ('caregiver', '代养人评价')], max_length=20)),
                ('rating', models.IntegerField(help_text='评分 1-5')),
                ('content', models.TextField(help_text='评价内容')),
                ('tags', models.JSONField(default=list, help_text='评价标签')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='api.order')),
                ('reviewee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_received', to=settings.AUTH_USER_MODEL)),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews_given', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('owner', '宠物主人'), ('caregiver', '代养人'), ('both', '双重身份')], default='owner', max_length=20)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('district', models.CharField(help_text='所在片区，如：朝阳区望京', max_length=100)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('latitude', models.FloatField(default=39.9042, help_text='纬度')),
                ('longitude', models.FloatField(default=116.4074, help_text='经度')),
                ('bio', models.TextField(blank=True, help_text='个人简介')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='caregiverprofile',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='caregiver', to='api.userprofile'),
        ),
        migrations.CreateModel(
            name='DailyRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_date', models.DateField()),
                ('feeding_info', models.TextField(help_text='喂养情况')),
                ('pet_status', models.TextField(help_text='宠物状态')),
                ('mood', models.CharField(blank=True, help_text='宠物心情', max_length=50)),
                ('abnormal_behavior', models.BooleanField(default=False, help_text='是否有异常行为')),
                ('abnormal_description', models.TextField(blank=True, help_text='异常行为描述')),
                ('photos', models.JSONField(default=list, help_text='状态照片URL列表')),
                ('notes', models.TextField(blank=True, help_text='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('caregiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_records', to='api.order')),
            ],
            options={
                'unique_together': {('order', 'record_date')},
            },
        ),
    ]
