# Generated by Django 6.0.6 on 2026-06-10 01:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='services',
            field=models.JSONField(default=list, help_text='服务项列表'),
        ),
        migrations.AddField(
            model_name='order',
            name='transport',
            field=models.CharField(choices=[('caregiver_pickup', '代养人上门接'), ('owner_deliver', '主人送上门'), ('meetup', '约定地点交接')], default='owner_deliver', help_text='接送方式', max_length=30),
        ),
        migrations.CreateModel(
            name='Dispute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('open', '协商中'), ('resolved', '已解决'), ('closed', '已关闭')], default='open', max_length=20)),
                ('trigger_type', models.CharField(choices=[('abnormal_behavior', '连续异常行为'), ('feeding_missing', '连续喂养缺失'), ('photo_missing', '连续照片缺失'), ('manual', '用户手动发起')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='争议描述')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolution', models.TextField(blank=True, help_text='解决方案')),
                ('escalation_alert_sent', models.BooleanField(default=False, help_text='是否已发送升级提醒')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes_initiated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='disputes', to='api.order')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='disputes_resolved', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DisputeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('owner', '宠物主人'), ('caregiver', '代养人'), ('system', '系统')], max_length=20)),
                ('content', models.TextField()),
                ('is_system', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='api.dispute')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dispute_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('reschedule', '改期'), ('services', '加减服务项'), ('transport', '修改接送方式'), ('price', '补差价/退款')], max_length=30)),
                ('status', models.CharField(choices=[('pending', '待确认'), ('approved', '已确认'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('original_start_date', models.DateField(blank=True, null=True)),
                ('original_end_date', models.DateField(blank=True, null=True)),
                ('new_start_date', models.DateField(blank=True, null=True)),
                ('new_end_date', models.DateField(blank=True, null=True)),
                ('original_services', models.JSONField(blank=True, default=list)),
                ('new_services', models.JSONField(blank=True, default=list)),
                ('original_transport', models.CharField(blank=True, choices=[('caregiver_pickup', '代养人上门接'), ('owner_deliver', '主人送上门'), ('meetup', '约定地点交接')], max_length=30, null=True)),
                ('new_transport', models.CharField(blank=True, choices=[('caregiver_pickup', '代养人上门接'), ('owner_deliver', '主人送上门'), ('meetup', '约定地点交接')], max_length=30, null=True)),
                ('original_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('new_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('price_diff', models.DecimalField(decimal_places=2, default=0, help_text='正数为补差价，负数为退款', max_digits=10)),
                ('reason', models.TextField(help_text='变更原因')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, help_text='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='changes_confirmed', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes_initiated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='api.order')),
            ],
        ),
    ]
