# Generated by Django 6.0.6 on 2026-06-10 05:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_order_services_order_transport_dispute_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Handover',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(choices=[('start', '开始服务交接'), ('end', '结束服务交接')], default='start', max_length=20)),
                ('status', models.CharField(choices=[('draft', '草稿'), ('pending_owner_confirm', '待主人确认'), ('pending_caregiver_confirm', '待代养人确认'), ('confirmed', '已确认'), ('disputed', '有争议')], default='draft', max_length=30)),
                ('items', models.JSONField(default=list, help_text='宠物随身物品清单，如：[{"name": "狗粮", "quantity": "2kg"}]')),
                ('feeding_instructions', models.TextField(blank=True, help_text='喂养/用药说明')),
                ('health_notes', models.TextField(blank=True, help_text='健康异常备注')),
                ('location', models.CharField(blank=True, help_text='接送地点', max_length=255)),
                ('photos', models.JSONField(default=list, help_text='交接照片URL列表')),
                ('expected_time', models.DateTimeField(blank=True, help_text='预计交接时间', null=True)),
                ('actual_items', models.JSONField(blank=True, default=list, help_text='代养人实际接收物品')),
                ('actual_notes', models.TextField(blank=True, help_text='代养人补充说明')),
                ('discrepancies', models.JSONField(blank=True, default=list, help_text='差异项列表，如：[{"field": "items", "description": "缺少狗粮1袋"}]')),
                ('has_discrepancies', models.BooleanField(default=False, help_text='是否存在差异或健康异常')),
                ('owner_confirmed', models.BooleanField(default=False)),
                ('caregiver_confirmed', models.BooleanField(default=False)),
                ('owner_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('caregiver_confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers_created', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='handovers', to='api.order')),
                ('related_dispute', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handovers', to='api.dispute')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
