# Generated by Django 6.0.6 on 2026-06-10 09:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_handover'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.DecimalField(decimal_places=2, help_text='托管总金额', max_digits=10)),
                ('platform_fee', models.DecimalField(decimal_places=2, default=0, help_text='平台服务费', max_digits=10)),
                ('caregiver_amount', models.DecimalField(decimal_places=2, default=0, help_text='代养人应收金额', max_digits=10)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='退款金额', max_digits=10)),
                ('status', models.CharField(choices=[('unpaid', '待支付'), ('held', '托管中'), ('settled', '已结算'), ('refunded', '已退款'), ('partially_refunded', '部分退款')], default='unpaid', max_length=30)),
                ('paid_at', models.DateTimeField(blank=True, help_text='支付托管时间', null=True)),
                ('settled_at', models.DateTimeField(blank=True, help_text='结算时间', null=True)),
                ('refunded_at', models.DateTimeField(blank=True, help_text='退款时间', null=True)),
                ('settlement_notes', models.TextField(blank=True, help_text='结算备注')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='escrow', to='api.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RefundRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='申请退款金额', max_digits=10)),
                ('reason', models.TextField(help_text='退款原因')),
                ('status', models.CharField(choices=[('pending', '待处理'), ('approved', '已同意'), ('rejected', '已拒绝'), ('cancelled', '已取消')], default='pending', max_length=20)),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('reject_reason', models.TextField(blank=True, help_text='拒绝原因')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='api.escrow')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_requests_handled', to=settings.AUTH_USER_MODEL)),
                ('initiator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests_initiated', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_requests', to='api.order')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
